# Generated by Django 5.2.8 on 2025-12-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='stock_descontado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='variante_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
