# Generated by Django 5.2.8 on 2025-12-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0003_pedido_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('SIN_FINALIZAR', 'Sin finalizar')], default='CREADO', max_length=20),
        ),
    ]
