# Generated by Django 5.2.8 on 2026-03-04 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0004_alter_pedido_estado'),
        ('pdf', '0019_pdfbranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDocSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceDocSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Lista Google Doc', max_length=120)),
                ('source_url', models.URLField()),
                ('doc_id', models.CharField(max_length=128)),
                ('last_modified_time', models.DateTimeField(blank=True, null=True)),
                ('last_revision_id', models.CharField(blank=True, max_length=128, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceDocItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(db_index=True, max_length=120)),
                ('producto', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='integraciones.pricedocsnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='pricedocsnapshot',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='integraciones.pricedocsource'),
        ),
        migrations.CreateModel(
            name='PriceUpdateCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(db_index=True, max_length=120)),
                ('producto_doc', models.CharField(blank=True, default='', max_length=255)),
                ('descripcion_doc', models.TextField(blank=True, default='')),
                ('old_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sku_match', models.CharField(blank=True, default='', max_length=120)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('venta_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('venta_sugerida', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pct_aumento_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('aplicado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('aplicado_en', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf.productoprecio')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='integraciones.pricedocsource')),
            ],
        ),
    ]
