# Generated by Django 5.2.8 on 2026-03-13 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0005_pricedocsnapshot_pricedocsource_pricedocitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricedocsource',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.RenameField(
            model_name='pricedocsource',
            old_name='last_modified_time',
            new_name='ultima_revision',
        ),
        migrations.RenameField(
            model_name='pricedocsource',
            old_name='source_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='pricedocsource',
            name='doc_id',
        ),
        migrations.RemoveField(
            model_name='pricedocsource',
            name='last_revision_id',
        ),
        migrations.AddField(
            model_name='pricedocsource',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_sources_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricedocsource',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_sources_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricedocsource',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricedocsource',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricedocsource',
            name='tipo',
            field=models.CharField(choices=[('google_sheet', 'Google Sheet'), ('google_doc', 'Google Doc'), ('pdf', 'PDF'), ('otro', 'Otro')], default='google_sheet', max_length=30),
        ),
        migrations.AddField(
            model_name='pricedocsource',
            name='ultimo_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pricedocsource',
            name='ultimo_estado',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pricedocsource',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
