# Generated by Django 5.2.8 on 2026-03-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0006_alter_pricedocsource_options_and_more'),
        ('pdf', '0019_pdfbranding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceupdatecandidate',
            options={'ordering': ['-creado_en']},
        ),
        migrations.AddField(
            model_name='pricedocsource',
            name='doc_id',
            field=models.CharField(default='legacy', help_text='ID del archivo en Google Drive / Google Docs', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricedocsource',
            name='last_modified_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricedocsource',
            name='last_revision_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pricedocsource',
            name='tipo',
            field=models.CharField(choices=[('google_doc', 'Google Doc'), ('google_sheet', 'Google Sheet'), ('docx_drive', 'DOCX en Drive'), ('pdf', 'PDF'), ('otro', 'Otro')], default='google_doc', max_length=30),
        ),
        migrations.AlterField(
            model_name='pricedocsource',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='priceupdatecandidate',
            index=models.Index(fields=['source', 'art'], name='integracion_source__3d9e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='priceupdatecandidate',
            index=models.Index(fields=['aprobado', 'aplicado'], name='integracion_aprobad_a7aff8_idx'),
        ),
    ]
