# Generated by Django 5.2.8 on 2026-09-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0007_alter_priceupdatecandidate_options_and_more'),
        ('pdf', '0019_pdfbranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('url', models.URLField(help_text='URL principal del proveedor.')),
                ('activo', models.BooleanField(default=True)),
                ('metodo', models.CharField(choices=[('manual', 'Manual'), ('html', 'HTML'), ('api', 'API')], default='html', max_length=20)),
                ('ultima_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoScrapeado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('imagen_url', models.URLField(blank=True, default='', max_length=1000)),
                ('url_producto', models.URLField(max_length=1000)),
                ('disponible', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='integraciones.scrapingproveedor')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_scraping', to='pdf.productoprecio')),
                ('producto_scrapeado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_catalogo', to='integraciones.productoscrapeado')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('producto_scrapeado', 'producto'), name='unique_producto_proveedor_scraping')],
            },
        ),
        migrations.AddIndex(
            model_name='productoscrapeado',
            index=models.Index(fields=['proveedor', 'nombre'], name='integracion_proveed_510ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='productoscrapeado',
            index=models.Index(fields=['disponible'], name='integracion_disponi_39848b_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoscrapeado',
            constraint=models.UniqueConstraint(fields=('proveedor', 'url_producto'), name='unique_producto_scrapeado_proveedor_url'),
        ),
    ]
