# Generated by Django 5.2.8 on 2026-09-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0008_scrapingproveedor_productoscrapeado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedocsource',
            name='doc_id',
            field=models.CharField(blank=True, help_text='ID del archivo en Drive (Dejar vacío si es web)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricedocsource',
            name='tipo',
            field=models.CharField(choices=[('google_doc', 'Google Doc'), ('google_sheet', 'Google Sheet'), ('docx_drive', 'DOCX en Drive'), ('pdf', 'PDF'), ('web_html', 'Scraping Web'), ('otro', 'Otro')], default='google_doc', max_length=30),
        ),
    ]
