# Generated by Django 5.2.8 on 2026-09-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0009_alter_pricedocsource_doc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedocitem',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
