# Generated by Django 5.2.8 on 2026-09-23 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integraciones', '0010_pricedocitem_imagen_url'),
        ('pdf', '0019_pdfbranding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceDocMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_proveedor', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.productoprecio')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculaciones', to='integraciones.pricedocsource')),
            ],
            options={
                'unique_together': {('source', 'art_proveedor')},
            },
        ),
    ]
