# Generated by Django 5.2.8 on 2026-01-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(choices=[('about', 'Quiénes somos'), ('work', 'Cómo trabajamos'), ('shipping', 'Métodos de envío'), ('warranty', 'Garantías'), ('other', 'Otro')], help_text='Identificador interno (no se muestra al cliente).', max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=80)),
                ('contenido', models.TextField(help_text='Texto que se muestra dentro del acordeón.')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
