# Generated by Django 5.2.8 on 2026-01-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_siteinfoblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=20)),
                ('secondary_color', models.CharField(default='#6c757d', max_length=20)),
                ('success_color', models.CharField(default='#198754', max_length=20)),
                ('danger_color', models.CharField(default='#dc3545', max_length=20)),
                ('background', models.CharField(default='#ffffff', max_length=20)),
                ('surface', models.CharField(default='#ffffff', max_length=20)),
                ('text_color', models.CharField(default='#111111', max_length=20)),
                ('font_base', models.CharField(default='system-ui, -apple-system, Segoe UI, Roboto, Arial', max_length=120)),
                ('font_headings', models.CharField(default='system-ui, -apple-system, Segoe UI, Roboto, Arial', max_length=120)),
                ('google_fonts_url', models.URLField(blank=True, default='')),
                ('texts', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
