# Generated by Django 5.2.8 on 2026-01-12 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_siteconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteinfoblock',
            options={'ordering': ('orden', 'id')},
        ),
        migrations.AddField(
            model_name='siteinfoblock',
            name='site',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='info_blocks', to='owner.siteconfig'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteinfoblock',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='siteinfoblock',
            name='clave',
            field=models.CharField(blank=True, help_text='Solo para uso interno. Si lo dejás vacío se genera desde el título.', max_length=80, verbose_name='Clave interna'),
        ),
        migrations.AlterField(
            model_name='siteinfoblock',
            name='contenido',
            field=models.TextField(blank=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='siteinfoblock',
            name='orden',
            field=models.PositiveIntegerField(default=1, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='siteinfoblock',
            name='titulo',
            field=models.CharField(max_length=120, verbose_name='Título'),
        ),
    ]
