# Generated by Django 5.2.8 on 2026-01-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_alter_siteinfoblock_options_siteinfoblock_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='muted_color',
            field=models.CharField(default='#6c757d', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='primary_rgb',
            field=models.CharField(default='13,110,253', help_text='Formato: R,G,B (ej: 13,110,253)', max_length=20),
        ),
    ]
