# Generated by Django 5.2.8 on 2026-01-12 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_siteconfig_muted_color_siteconfig_primary_rgb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('carrito_add', 'Carrito: producto agregado'), ('carrito_remove', 'Carrito: producto eliminado'), ('compra_creada', 'Compra realizada'), ('compra_cancelada', 'Compra cancelada'), ('producto_creado', 'Producto creado'), ('producto_editado', 'Producto editado'), ('producto_eliminado', 'Producto eliminado'), ('precio_actualizado', 'Precio actualizado'), ('rubros_asignados', 'Rubros asignados / auto-rubros'), ('siteconfig_edit', 'Personalización del sitio modificada'), ('siteinfo_edit', 'Información del sitio modificada'), ('lista_cargada', 'Lista de precios cargada'), ('factura_proveedor_cargada', 'Factura de proveedor cargada'), ('factura_pdf_generada', 'Factura PDF generada')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('detalle', models.TextField(blank=True)),
                ('obj_model', models.CharField(blank=True, max_length=100)),
                ('obj_id', models.CharField(blank=True, max_length=50)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacora_eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
