# Generated by Django 5.2.8 on 2026-01-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_bitacoraevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraevento',
            name='tipo',
            field=models.CharField(choices=[('carrito_agregar', 'Carrito: producto agregado'), ('carrito_eliminar', 'Carrito: producto eliminado'), ('carrito_actualizar', 'Carrito: cantidad actualizada'), ('carrito_vaciar', 'Carrito: carrito vaciado'), ('carrito_agregar_sin_stock', 'Carrito: intento de agregar sin stock'), ('carrito_sin_stock', 'Carrito: producto quitado por falta de stock'), ('cupon_aplicado', 'Cupón aplicado'), ('cupon_invalido', 'Cupón inválido o vencido'), ('favorito_agregar', 'Favoritos: producto agregado'), ('favorito_eliminar', 'Favoritos: producto eliminado'), ('compra_creada', 'Compra realizada'), ('compra_cancelada', 'Compra cancelada'), ('pedido_ver_detalle', 'Pedido: ver detalle'), ('pedido_continuar_pago', 'Pedido: continuar pago'), ('pedido_continuar_no_permitido', 'Pedido: continuar no permitido'), ('pedido_continuar_sin_link', 'Pedido: continuar sin link de pago'), ('pedido_cancelar', 'Pedido: cancelado por el cliente'), ('pedido_cancelar_no_permitido', 'Pedido: intento de cancelación no permitida'), ('pedido_eliminar', 'Pedido: eliminado por el cliente'), ('pedido_eliminar_no_permitido', 'Pedido: intento de eliminación no permitida'), ('producto_creado', 'Producto creado'), ('producto_editado', 'Producto editado'), ('producto_eliminado', 'Producto eliminado'), ('precio_actualizado', 'Precio actualizado'), ('productos_bulk_activar', 'Productos: alta masiva'), ('productos_bulk_desactivar', 'Productos: baja masiva'), ('productos_bulk_eliminar', 'Productos: eliminación masiva'), ('productos_bulk_tech', 'Productos: técnica asignada masivamente'), ('rubros_asignados', 'Rubros asignados / auto-rubros'), ('autorubros_aplicados', 'Auto-rubros aplicados'), ('rubro_creado', 'Rubro creado'), ('rubro_editado', 'Rubro editado'), ('rubro_eliminado', 'Rubro eliminado'), ('subrubro_creado', 'Subrubro creado'), ('subrubro_editado', 'Subrubro editado'), ('subrubro_eliminado', 'Subrubro eliminado'), ('siteconfig_edit', 'Personalización del sitio modificada'), ('siteinfo_edit', 'Información del sitio modificada'), ('perfil_actualizado', 'Perfil de usuario actualizado'), ('lista_cargada', 'Lista de precios cargada'), ('lista_import_confirmada', 'Importación de lista confirmada'), ('factura_proveedor_cargada', 'Factura de proveedor cargada'), ('factura_proveedor_confirmada', 'Factura de proveedor confirmada'), ('factura_pdf_generada', 'Factura PDF generada'), ('lista_precios_pdf_generada', 'Lista de precios PDF generada'), ('logout', 'Usuario cerró sesión')], max_length=50),
        ),
    ]
