# Generated by Django 5.2.8 on 2026-01-12 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0007_alter_bitacoraevento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraevento',
            name='archivo',
            field=models.FileField(blank=True, help_text='Adjunto opcional (PDF, CSV, etc.) relacionado al evento.', null=True, upload_to='bitacora/'),
        ),
    ]
