# Generated by Django 5.2.8 on 2026-03-19 23:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_bitacoraevento_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraevento',
            name='tipo',
            field=models.CharField(choices=[('carrito_agregar', 'Carrito: producto agregado'), ('carrito_eliminar', 'Carrito: producto eliminado'), ('carrito_actualizar', 'Carrito: cantidad actualizada'), ('carrito_vaciar', 'Carrito: carrito vaciado'), ('carrito_agregar_sin_stock', 'Carrito: intento de agregar sin stock'), ('carrito_sin_stock', 'Carrito: producto quitado por falta de stock'), ('cupon_aplicado', 'Cupón aplicado'), ('cupon_invalido', 'Cupón inválido o vencido'), ('favorito_agregar', 'Favoritos: producto agregado'), ('favorito_eliminar', 'Favoritos: producto eliminado'), ('compra_creada', 'Compra realizada'), ('compra_cancelada', 'Compra cancelada'), ('pedido_ver_detalle', 'Pedido: ver detalle'), ('pedido_continuar_pago', 'Pedido: continuar pago'), ('pedido_continuar_no_permitido', 'Pedido: continuar no permitido'), ('pedido_continuar_sin_link', 'Pedido: continuar sin link de pago'), ('pedido_cancelar', 'Pedido: cancelado por el cliente'), ('pedido_cancelar_no_permitido', 'Pedido: intento de cancelación no permitida'), ('pedido_eliminar', 'Pedido: eliminado por el cliente'), ('pedido_eliminar_no_permitido', 'Pedido: intento de eliminación no permitida'), ('producto_creado', 'Producto creado'), ('producto_editado', 'Producto editado'), ('producto_eliminado', 'Producto eliminado'), ('precio_actualizado', 'Precio actualizado'), ('productos_bulk_activar', 'Productos: alta masiva'), ('productos_bulk_desactivar', 'Productos: baja masiva'), ('productos_bulk_eliminar', 'Productos: eliminación masiva'), ('productos_bulk_tech', 'Productos: técnica asignada masivamente'), ('venta_registrada', 'Venta registrada'), ('venta_eliminada', 'Venta eliminada'), ('rubros_asignados', 'Rubros asignados / auto-rubros'), ('autorubros_aplicados', 'Auto-rubros aplicados'), ('rubro_creado', 'Rubro creado'), ('rubro_editado', 'Rubro editado'), ('rubro_eliminado', 'Rubro eliminado'), ('subrubro_creado', 'Subrubro creado'), ('subrubro_editado', 'Subrubro editado'), ('subrubro_eliminado', 'Subrubro eliminado'), ('siteconfig_edit', 'Personalización del sitio modificada'), ('siteinfo_edit', 'Información del sitio modificada'), ('perfil_actualizado', 'Perfil de usuario actualizado'), ('lista_cargada', 'Lista de precios cargada'), ('lista_import_confirmada', 'Importación de lista confirmada'), ('factura_proveedor_cargada', 'Factura de proveedor cargada'), ('factura_proveedor_confirmada', 'Factura de proveedor confirmada'), ('factura_pdf_generada', 'Factura PDF generada'), ('lista_precios_pdf_generada', 'Lista de precios PDF generada'), ('logout', 'Usuario cerró sesión')], max_length=50),
        ),
        migrations.CreateModel(
            name='VentaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacion', models.CharField(blank=True, default='', max_length=255)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_rapidas', to='owner.productoprecio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_rapidas_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta rápida',
                'verbose_name_plural': 'Ventas rápidas',
                'ordering': ('-fecha', '-id'),
            },
        ),
    ]
