# Generated by Django 5.2.8 on 2026-03-19 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_alter_bitacoraevento_tipo_ventarapida'),
        ('pdf', '0019_pdfbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventarapida',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_rapidas', to='pdf.productoprecio'),
        ),
        migrations.DeleteModel(
            name='ProductoPrecio',
        ),
    ]
