# Generated by Django 5.2.8 on 2026-03-20 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_alter_ventarapida_producto_delete_productoprecio'),
        ('pdf', '0019_pdfbranding'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventarapida',
            name='medio_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], default='transferencia', max_length=20),
        ),
        migrations.AddField(
            model_name='ventarapida',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_rapidas', to='pdf.productovariante'),
        ),
    ]
