# Generated by Django 5.2.8 on 2026-03-20 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_ventarapida_medio_pago_ventarapida_variante'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('imagen', models.ImageField(upload_to='site/carousel/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_images', to='owner.siteconfig')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
