# Generated by Django 5.2.8 on 2026-09-22 02:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_sitecarouselimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventarapida',
            name='es_senia',
            field=models.BooleanField(default=False, verbose_name='¿Es seña?'),
        ),
        migrations.AddField(
            model_name='ventarapida',
            name='medio_pago_senia',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ventarapida',
            name='monto_senia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='ventarapida',
            name='pagado_completo',
            field=models.BooleanField(default=True, verbose_name='¿Pagado completo?'),
        ),
    ]
