# Generated by Django 5.2.8 on 2025-12-01 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_facturaproveedor_itemfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoprecio',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='lista_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_precio_pdf', to='pdf.listapreciopdf'),
        ),
    ]
