# Generated by Django 5.2.8 on 2025-12-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_facturaproveedor_itemfactura'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoprecio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
