# Generated by Django 5.2.8 on 2025-12-02 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_productoprecio_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoprecio',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='tech',
            field=models.CharField(blank=True, choices=[('SUB', 'Sublimación'), ('LAS', 'Grabado láser'), ('3D', 'Impresión 3D'), ('OTR', 'Otro')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='lista_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='pdf.listapreciopdf'),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
