# Generated by Django 5.2.8 on 2025-12-06 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_productoprecio_imagen'),
        ('pdf', '0004_remove_productoprecio_cantidad_productoprecio_activo_and_more'),
    ]

    operations = [
    ]
