# Generated by Django 5.2.8 on 2025-12-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0005_merge_20251205_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoprecio',
            name='precio_costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
