# Generated by Django 5.2.8 on 2025-12-14 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0007_producto_productovariante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='pdf.productoprecio'),
        ),
        migrations.AlterModelOptions(
            name='productovariante',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.RenameField(
            model_name='productovariante',
            old_name='descripcion_variante',
            new_name='descripcion_corta',
        ),
        migrations.RemoveField(
            model_name='productovariante',
            name='nombre_variante',
        ),
        migrations.RemoveField(
            model_name='productovariante',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='productovariante',
            name='sku',
        ),
        migrations.AddField(
            model_name='productovariante',
            name='nombre',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productovariante',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
