# Generated by Django 5.2.8 on 2025-12-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0008_alter_productovariante_producto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together={('producto', 'nombre')},
        ),
        migrations.AlterField(
            model_name='productovariante',
            name='descripcion_corta',
            field=models.CharField(blank=True, help_text='Breve descripción de esta variante', max_length=255),
        ),
        migrations.AlterField(
            model_name='productovariante',
            name='nombre',
            field=models.CharField(help_text='Ej: Rojo, Azul, Negro', max_length=100),
        ),
        migrations.RemoveField(
            model_name='productovariante',
            name='stock',
        ),
    ]
