# Generated by Django 5.2.8 on 2025-12-14 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_alter_productovariante_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productovariante',
            options={'ordering': ['orden', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='productovariante',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productovariante',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productovariante',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productovariante',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productovariante',
            name='descripcion_corta',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='productovariante',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
    ]
