# Generated by Django 5.2.8 on 2025-12-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0010_alter_productovariante_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoprecio',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
    ]
