# Generated by Django 5.2.8 on 2025-12-17 02:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0011_productoprecio_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('vendedor_nombre', models.CharField(default='Mundo Personalizado', max_length=120)),
                ('vendedor_whatsapp', models.CharField(default='11 5663-7260', max_length=50)),
                ('vendedor_horario', models.CharField(default='9:00 a 20:00', max_length=80)),
                ('vendedor_direccion', models.CharField(default='Virrey del Pino, La Matanza', max_length=160)),
                ('cliente_nombre', models.CharField(max_length=140)),
                ('cliente_telefono', models.CharField(blank=True, max_length=60)),
                ('cliente_doc', models.CharField(blank=True, max_length=60)),
                ('cliente_direccion', models.CharField(blank=True, max_length=180)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pdf.factura')),
            ],
        ),
    ]
