# Generated by Django 5.2.8 on 2025-12-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0012_factura_facturaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productovariante',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
