# Generated by Django 5.2.8 on 2025-12-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0013_alter_productovariante_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoprecio',
            name='rubro',
            field=models.CharField(choices=[('MATES', 'Mates'), ('DIJES', 'Dijes de acero'), ('BOMB', 'Bombillas'), ('TERM', 'Termos'), ('TAZA', 'Tazas'), ('LLAV', 'Llaveros'), ('OTRO', 'Otros')], default='OTRO', max_length=10),
        ),
        migrations.AddField(
            model_name='productoprecio',
            name='subrubro',
            field=models.CharField(blank=True, default='', help_text='Ej: Imperial, Camionero, Acero, Plástico, etc.', max_length=80),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-29 23:35'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='tech',
            field=models.CharField(choices=[('SUB', 'Sublimación'), ('LAS', 'Grabado láser'), ('3D', 'Impresión 3D'), ('OTR', 'Otro')], default='OTR', max_length=3),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, default='2025-12-29 23:35'),
            preserve_default=False,
        ),
    ]
