# Generated by Django 5.2.8 on 2025-12-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0014_productoprecio_rubro_productoprecio_subrubro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoprecio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='rubro',
            field=models.CharField(blank=True, default='', help_text='Ej: Mates, Dijes de acero, Tazas, Llaveros...', max_length=80),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='subrubro',
            field=models.CharField(blank=True, default='', help_text='Ej: Mate Imperial, Mate Camionero, Dije corazón, etc.', max_length=80),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='tech',
            field=models.CharField(blank=True, choices=[('SUB', 'Sublimación'), ('LAS', 'Grabado láser'), ('3D', 'Impresión 3D'), ('OTR', 'Otro')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='productoprecio',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
