# Generated by Django 5.2.8 on 2025-12-30 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0015_alter_productoprecio_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tech', models.CharField(blank=True, choices=[('SUB', 'Sublimación'), ('LAS', 'Grabado láser'), ('3D', 'Impresión 3D'), ('OTR', 'Otro')], default='', max_length=3)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='SubRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='pdf.rubro')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
                'unique_together': {('rubro', 'nombre')},
            },
        ),
    ]
