# Generated by Django 5.2.8 on 2026-01-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0016_rubro_subrubro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubro',
            name='nombre',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='rubro',
            unique_together={('nombre', 'tech')},
        ),
    ]
