# Generated by Django 5.2.8 on 2026-01-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0017_alter_rubro_nombre_alter_rubro_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='productovariante',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si lo dejás vacío, se usa el precio del producto.', max_digits=10, null=True, verbose_name='Precio de la variante'),
        ),
    ]
