# Generated by Django 5.2.8 on 2026-01-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0018_productovariante_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watermark', models.ImageField(blank=True, null=True, upload_to='branding/')),
            ],
        ),
    ]
