# Generated by Django 5.2.8 on 2025-12-12 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdf', '0005_merge_20251205_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('porcentaje_descuento', models.PositiveIntegerField()),
                ('usos_disponibles', models.PositiveIntegerField(default=1)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf.productoprecio')),
            ],
        ),
    ]
