# Generated by Django 5.2.8 on 2025-12-12 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cupon',
        ),
    ]
