# Generated by Django 5.2.8 on 2025-12-15 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='creado',
        ),
        migrations.AddField(
            model_name='cupon',
            name='tecnica',
            field=models.CharField(choices=[('TODAS', 'Todas'), ('SUBLIMACION', 'Sublimación'), ('LASER', 'Láser'), ('3D', 'Impresión 3D'), ('OTRO', 'Otro')], default='TODAS', max_length=20),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='descuento',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
