# Generated by Django 5.2.8 on 2025-12-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0004_remove_cupon_creado_cupon_tecnica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='tecnica',
            field=models.CharField(choices=[('TODAS', 'Todas'), ('SUBLIMACION', 'Sublimación'), ('LASER', 'Grabado láser'), ('IMPRESION_3D', 'Impresión 3D'), ('OTRO', 'Otro')], default='TODAS', max_length=20),
        ),
    ]
