# Generated by Django 5.2.8 on 2025-12-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupones', '0005_alter_cupon_tecnica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupon',
            name='tecnica',
            field=models.CharField(choices=[('TODAS', 'Todas'), ('SUB', 'Sublimación'), ('LAS', 'Grabado láser'), ('3D', 'Impresión 3D'), ('OTR', 'Otro')], default='TODAS', max_length=20),
        ),
    ]
