# Generated by Django 5.2.8 on 2025-12-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tecnica', models.CharField(choices=[('ALL', 'Todos'), ('SUB', 'Sublimación'), ('LAS', 'Láser'), ('3D', 'Impresión 3D'), ('OTR', 'Otro')], default='ALL', max_length=3)),
                ('descuento', models.PositiveIntegerField(help_text='Porcentaje de descuento')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
