# Generated by Django 5.2.8 on 2025-12-15 03:50

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='activa',
        ),
        migrations.AddField(
            model_name='oferta',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='descuento',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='tecnica',
            field=models.CharField(choices=[('TODAS', 'Todas'), ('SUB', 'Sublimación'), ('LAS', 'Grabado láser'), ('3D', 'Impresión 3D'), ('OTR', 'Otro')], default='TODAS', max_length=20),
        ),
    ]
