# Generated by Django 5.2.8 on 2025-12-15 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_remove_oferta_activa_oferta_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='tecnica',
        ),
        migrations.AddField(
            model_name='oferta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='tecnicas',
            field=models.JSONField(blank=True, help_text="Ej: ['SUB', 'LAS']", null=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tipo_descuento',
            field=models.CharField(choices=[('PCT', 'Porcentaje'), ('FIJ', 'Monto fijo')], default='PCT', max_length=3),
        ),
        migrations.AddField(
            model_name='oferta',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje (ej: 20) o monto fijo', max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oferta',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
